version: '3'
services:
  elasticsearch:
    build: elasticsearch
    image: elasticsearch
    container_name: elasticsearch
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
      - "xpack.monitoring.enabled=false"
      - "xpack.watcher.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.ml.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - ALL
    volumes:
      - ./data-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    build: kibana
    image: kibana
    container_name: kibana
    environment:
      - "I18N_LOCALE=ja-JP"
    volumes:
      - ./data-kibana:/usr/share/kibana/data
    ports:
      - 5601:5601
