FROM docker.elastic.co/kibana/kibana:7.0.1
RUN curl -L https://github.com/tak7iji/kibana/raw/i18n-ja/x-pack/plugins/translations/translations/ja-JP.json -o /opt/kibana/node_modules/x-pack/plugins/translations/translations/ja-JP.json
